USE ROLE ACCOUNTADMIN;
USE WAREHOUSE LOGISTICS_WH;
USE DATABASE LOGISTICS_DB;
USE SCHEMA SUPPLY_CHAIN_SCHEMA;

CREATE OR REPLACE PIPE SHIPMENT_PIPE
AUTO_INGEST = FALSE
AS
COPY INTO SHIPMENT
FROM @LOGISTICS_STAGE/Shipment.csv
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);
SHOW PIPES;

ALTER PIPE SHIPMENT_PIPE REFRESH;
SELECT SYSTEM$PIPE_STATUS('SHIPMENT_PIPE');

SELECT COUNT(*) FROM SHIPMENT;

DELETE FROM SHIPMENT
WHERE shipmentId = 'S99999';

SELECT *
FROM SHIPMENT
WHERE shipmentId = 'S99999';

SELECT *
FROM SHIPMENT
AT (OFFSET => -60*5)
WHERE shipmentId = 'S99999';

SELECT *
FROM SHIPMENT
WHERE shipmentId = 'S99999';

CREATE OR REPLACE DATABASE LOGISTICS_CLONE_DB
CLONE LOGISTICS_DB;
SHOW DATABASES;

SELECT *
FROM LOGISTICS_CLONE_DB.SUPPLY_CHAIN_SCHEMA.SHIPMENT
LIMIT 10;

SELECT
    shipmentStatus,
    COUNT(*) AS total_shipments
FROM SHIPMENT
GROUP BY shipmentStatus;

ALTER TABLE SHIPMENT
CLUSTER BY (shipmentStatus);

SELECT *
FROM SHIPMENT
WHERE shipmentStatus = 'Delayed';

SELECT *
FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
ORDER BY START_TIME DESC;

CREATE OR REPLACE VIEW VW_LOGISTICS_KPI AS
SELECT
    shipmentStatus,
    COUNT(*) AS total_shipments,
    AVG(shipmentWeight) AS avg_weight,
    SUM(shipmentWeight) AS total_weight
FROM SHIPMENT
GROUP BY shipmentStatus;

SELECT * FROM VW_LOGISTICS_KPI;
