USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE logistics_admin;
CREATE OR REPLACE ROLE logistics_analyst;
CREATE OR REPLACE ROLE logistics_operator;

GRANT USAGE
ON WAREHOUSE LOGISTICS_WH
TO ROLE logistics_admin;

GRANT USAGE
ON WAREHOUSE LOGISTICS_WH
TO ROLE logistics_analyst;

GRANT USAGE
ON WAREHOUSE LOGISTICS_WH
TO ROLE logistics_operator;

GRANT USAGE
ON DATABASE LOGISTICS_DB
TO ROLE logistics_admin;

GRANT USAGE
ON DATABASE LOGISTICS_DB
TO ROLE logistics_analyst;

GRANT USAGE
ON DATABASE LOGISTICS_DB
TO ROLE logistics_operator;

GRANT USAGE
ON SCHEMA LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA
TO ROLE logistics_admin;

GRANT USAGE
ON SCHEMA LOGISTICS_DB.ANALYTICS_SCHEMA
TO ROLE logistics_admin;

GRANT USAGE
ON SCHEMA LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA
TO ROLE logistics_analyst;

GRANT USAGE
ON SCHEMA LOGISTICS_DB.ANALYTICS_SCHEMA
TO ROLE logistics_analyst;

GRANT USAGE
ON SCHEMA LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA
TO ROLE logistics_operator;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA
TO ROLE logistics_admin;

GRANT ALL PRIVILEGES
ON ALL TABLES IN SCHEMA LOGISTICS_DB.ANALYTICS_SCHEMA
TO ROLE logistics_admin;

GRANT SELECT
ON ALL TABLES IN SCHEMA LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA
TO ROLE logistics_analyst;

GRANT SELECT
ON ALL TABLES IN SCHEMA LOGISTICS_DB.ANALYTICS_SCHEMA
TO ROLE logistics_analyst;

GRANT SELECT, INSERT, UPDATE
ON TABLE LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA.SHIPMENT
TO ROLE logistics_operator;

SHOW ROLES;

USE ROLE ACCOUNTADMIN;
USE DATABASE LOGISTICS_DB;
USE SCHEMA ANALYTICS_SCHEMA;
CREATE OR REPLACE SECURE VIEW SECURE_DRIVER_VIEW AS
SELECT
    driverId,
    driverName,

    CASE
        WHEN CURRENT_ROLE() = 'LOGISTICS_ADMIN'
            THEN contactNumber
        ELSE 'XXXXXXXXXX'
    END AS contactNumber

FROM LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA.DRIVER;

CREATE OR REPLACE SECURE VIEW SECURE_DRIVERS_VIEW AS
SELECT
    driverId,
    driverName,
    contactNumber
FROM LOGISTICS_DB.SUPPLY_CHAIN_SCHEMA.DRIVER;
SELECT * FROM SECURE_DRIVER_VIEW LIMIT 10;

GRANT SELECT
ON FUTURE TABLES IN SCHEMA LOGISTICS_DB.ANALYTICS_SCHEMA
TO ROLE logistics_analyst;

SHOW GRANTS TO ROLE logistics_analyst;

